<a href="https://colab.research.google.com/github/FaroghZahra/Classification/blob/main/IRIS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
#importing iris dataset
from sklearn.datasets import load_iris

In [4]:
#loading iris dataset
iris = load_iris()

In [5]:
X = iris.data

In [6]:
y = iris.target
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [7]:
#class 0 -->[1,0,0]
#class 1 --->[0,1,0]
#class 2 --->[0,0,1]

#for 1 hot encoding

In [8]:
from keras.utils import to_categorical

In [9]:
y = to_categorical(y)

In [11]:
y.shape
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.30,random_state=42)

In [15]:
#scale network

from sklearn.preprocessing import MinMaxScaler
scaler_object = MinMaxScaler()
scaler_object.fit(X_train)

scaled_X_train = scaler_object.transform(X_train)
scaled_X_test = scaler_object.transform(X_test)

print(scaled_X_test)

[[ 0.52941176  0.36363636  0.64285714  0.45833333]
 [ 0.41176471  0.81818182  0.10714286  0.08333333]
 [ 1.          0.27272727  1.03571429  0.91666667]
 [ 0.5         0.40909091  0.60714286  0.58333333]
 [ 0.73529412  0.36363636  0.66071429  0.54166667]
 [ 0.32352941  0.63636364  0.07142857  0.125     ]
 [ 0.38235294  0.40909091  0.44642857  0.5       ]
 [ 0.76470588  0.5         0.71428571  0.91666667]
 [ 0.55882353  0.09090909  0.60714286  0.58333333]
 [ 0.44117647  0.31818182  0.5         0.45833333]
 [ 0.64705882  0.54545455  0.71428571  0.79166667]
 [ 0.14705882  0.45454545  0.05357143  0.        ]
 [ 0.35294118  0.68181818  0.03571429  0.04166667]
 [ 0.17647059  0.5         0.07142857  0.        ]
 [ 0.23529412  0.81818182  0.07142857  0.08333333]
 [ 0.58823529  0.59090909  0.64285714  0.625     ]
 [ 0.64705882  0.45454545  0.83928571  0.875     ]
 [ 0.38235294  0.22727273  0.5         0.41666667]
 [ 0.41176471  0.36363636  0.60714286  0.5       ]
 [ 0.61764706  0.36363636  0.80

In [17]:
from keras.models import Sequential
from keras.layers import Dense

In [20]:
model = Sequential()
model.add(Dense(8,input_dim=4,activation='relu'))
model.add(Dense(8,input_dim=4,activation='relu'))
model.add(Dense(3,activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [21]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_5 (Dense)             (None, 8)                 40        
                                                                 
 dense_6 (Dense)             (None, 8)                 72        
                                                                 
 dense_7 (Dense)             (None, 3)                 27        
                                                                 
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [42]:
model.fit(scaled_X_train, y_train, epochs = 100, verbose=2)

Epoch 1/100
4/4 - 0s - loss: 0.3381 - accuracy: 0.9333 - 46ms/epoch - 11ms/step
Epoch 2/100
4/4 - 0s - loss: 0.3359 - accuracy: 0.9524 - 34ms/epoch - 9ms/step
Epoch 3/100
4/4 - 0s - loss: 0.3338 - accuracy: 0.9524 - 32ms/epoch - 8ms/step
Epoch 4/100
4/4 - 0s - loss: 0.3318 - accuracy: 0.9524 - 27ms/epoch - 7ms/step
Epoch 5/100
4/4 - 0s - loss: 0.3296 - accuracy: 0.9524 - 29ms/epoch - 7ms/step
Epoch 6/100
4/4 - 0s - loss: 0.3270 - accuracy: 0.9524 - 32ms/epoch - 8ms/step
Epoch 7/100
4/4 - 0s - loss: 0.3255 - accuracy: 0.9524 - 21ms/epoch - 5ms/step
Epoch 8/100
4/4 - 0s - loss: 0.3231 - accuracy: 0.9524 - 13ms/epoch - 3ms/step
Epoch 9/100
4/4 - 0s - loss: 0.3208 - accuracy: 0.9524 - 14ms/epoch - 4ms/step
Epoch 10/100
4/4 - 0s - loss: 0.3186 - accuracy: 0.9524 - 12ms/epoch - 3ms/step
Epoch 11/100
4/4 - 0s - loss: 0.3164 - accuracy: 0.9524 - 14ms/epoch - 4ms/step
Epoch 12/100
4/4 - 0s - loss: 0.3144 - accuracy: 0.9524 - 13ms/epoch - 3ms/step
Epoch 13/100
4/4 - 0s - loss: 0.3121 - accuracy:

In [43]:
scaled_X_test

array([[ 0.52941176,  0.36363636,  0.64285714,  0.45833333],
       [ 0.41176471,  0.81818182,  0.10714286,  0.08333333],
       [ 1.        ,  0.27272727,  1.03571429,  0.91666667],
       [ 0.5       ,  0.40909091,  0.60714286,  0.58333333],
       [ 0.73529412,  0.36363636,  0.66071429,  0.54166667],
       [ 0.32352941,  0.63636364,  0.07142857,  0.125     ],
       [ 0.38235294,  0.40909091,  0.44642857,  0.5       ],
       [ 0.76470588,  0.5       ,  0.71428571,  0.91666667],
       [ 0.55882353,  0.09090909,  0.60714286,  0.58333333],
       [ 0.44117647,  0.31818182,  0.5       ,  0.45833333],
       [ 0.64705882,  0.54545455,  0.71428571,  0.79166667],
       [ 0.14705882,  0.45454545,  0.05357143,  0.        ],
       [ 0.35294118,  0.68181818,  0.03571429,  0.04166667],
       [ 0.17647059,  0.5       ,  0.07142857,  0.        ],
       [ 0.23529412,  0.81818182,  0.07142857,  0.08333333],
       [ 0.58823529,  0.59090909,  0.64285714,  0.625     ],
       [ 0.64705882,  0.

In [44]:
predict=model.predict(scaled_X_test) 
predictions=np.argmax(predict,axis=1)
predictions

2/2 [==============================] - 0s 6ms/step


array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0])

In [46]:
#converting y_test in predicted y format
test_y = y_test.argmax(axis=1)

In [47]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [48]:
confusion_matrix(test_y,predictions)

array([[19,  0,  0],
       [ 0, 12,  1],
       [ 0,  0, 13]])

In [49]:
print(classification_report(test_y,predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.92      0.96        13
           2       0.93      1.00      0.96        13

    accuracy                           0.98        45
   macro avg       0.98      0.97      0.97        45
weighted avg       0.98      0.98      0.98        45



In [50]:
accuracy_score(test_y,predictions)

0.9777777777777777